apiVersion: apps/v1
kind: Deployment
metadata:
  name: newscenter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newscenter
  template:
    metadata:
      labels:
        app: newscenter
    spec:
      containers:
        - name: newscenter-api
          image: teromonte/newscenter-api:v3
          imagePullPolicy: Always # Uncomment this when testing cloud deployment
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
          # We still mount the ChromaDB volume
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/chroma_db
      volumes:
        - name: chroma-storage
          hostPath:
            # Update 'thiag' to your user
            path: /home/ubuntu/genai_data/chroma_db
            type: DirectoryOrCreate
