apiVersion: v1
kind: Service
metadata:
  name: newsbot-frontend-service
spec:
  selector:
    app: newsbot-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
