apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsbot-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsbot-frontend
  template:
    metadata:
      labels:
        app: newsbot-frontend
    spec:
      containers:
        - name: newsbot-frontend
          image: teromonte/newsbot-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://newscenter-service:8000"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
