apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newscenter-ingress
  annotations:
    # Tell K8s to use the Nginx controller we just installed
    kubernetes.io/ingress.class: nginx
    # Optional: remove limits on upload size if you send large data
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: newsbot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newscenter-service
            port:
              number: 8000