apiVersion: v1
kind: Service
metadata:
  name: newscenter-service
spec:
  type: LoadBalancer
  selector:
    app: newscenter
  ports:
    - protocol: TCP
      port: 8000      # The port accessible outside
      targetPort: 8000 # The port inside the container